version: '2.0'

services:
    node:
        build: .
        volumes:
          - ../recipe-pictures-old/original/:/var/data/original
          - ../recipe-pictures-old/watermark.png:/var/data/watermark.png
          - ./gulpfile.js:/var/data/gulpfile.js
          - ../recipe-pictures-old/generated/:/var/data/generated
